name: Deploy

on:
  push:
    branches: ["dev"]

jobs:
  Deploy:
    name: Deploy to lightsail
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/bitnami/projects/Refine-Dashboard
            git checkout dev
            git fetch origin dev
            git pull origin dev
            cd server
            npm install
            forever start index.js
